### ISSUE TITLE
Sndfile version

### ISSUE THREAD

**Issue by klapaciuss** [hzeller/folve#2]
Hello. 

When folve is starting there is message "This sndfile version has known issues writing headers. Switching to compatibility mode. Please use version > 1.0.29 of libsndfile". 

But there is not required version neither in repository (1.0.27) neither on libsnd homepage (1.0.28). What is influenced by above mentioned compatibilty mode?

Debian 9.5, 64bit.

Regards.

Marek

**Comment by hzeller** [comment]
Yeah, libsndfile is released relatively rarely, so you have to compile it [from source](https://github.com/erikd/libsndfile).

I've fixed the issue in question in a [pull request to libsndfile](https://github.com/erikd/libsndfile/commit/a81308ee40dc11ebffa2740272b611170f069ec7), but since then not a new release has been published.

**Comment by hzeller** [comment]
The implications with the workaround are that the flac header is more generic. Usually, folve will try to preserve as much as possible from the original flac header, but with the issue in libsndfile this is not possible, so it generates a more generic header which means loss of some metadata. So it is probably a good idea to get a current version of libsndfile.

**Comment by klapaciuss** [comment]
Thanks. Problem solved.

Btw. MPD currently supports streaming from Tidal. Is it possible to use folve for convolution during tidal stream playback in mpd?

Regards.

Marek

**Comment by hzeller** [comment]
folve currently can only convolve files presentet in a filesystem. But maybe you can use jack to convolve streams?

**Comment by klapaciuss** [comment]
Hello.

Currently I am installing provided last version of libsndfile library version on different system (Debian 8). Standard compilation steps works OK, "make check" returns OK result with correct version of library. But folve during start detects old version of library and compatibility mode is started. It seem that there are two versions of libsndfile on system. How to force folve to use right version?

Regards.

Marek

**Comment by hzeller** [comment]
Did you `sudo make install` the libsndfile ?
Also, you need to re-compile folve after you have installed the libsndfile.

It might also be a good idea to actually remove the old version `sudo apt-get remove libsndfile-dev`

**Comment by hzeller** [comment]
^ I've added support that the position of the include file and library is extracted from `pkg-config`, so that two installation options would work.

(also, always make sure to run `ldconfig` when you compile and install libsndfile)
